version: '3.9'
services:
  postgres:
    image: postgres:13
  redis:
    image: redis:6
  kafka:
    image: bitnami/kafka:2.8
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
  clickhouse:
    image: clickhouse/clickhouse-server:21.8
  opensearch:
    image: opensearchproject/opensearch:1.3.0
